In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.3.0


In [3]:
hello = tf.constant('Hello')

In [4]:
world = tf.constant("World")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [8]:
with tf.Session() as sess:
    result  = sess.run(hello+world)

In [9]:
print(result)

b'HelloWorld'


In [10]:
a = tf.constant(10)

In [11]:
b = tf.constant(20)

In [12]:
type(a)

tensorflow.python.framework.ops.Tensor

In [13]:
a+b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [14]:
a+b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [15]:
a+b

<tf.Tensor 'add_4:0' shape=() dtype=int32>

In [16]:
 with tf.Session() as sess:
        result = sess.run(a+b)

In [17]:
result

30

In [18]:
const = tf.constant(10)

In [19]:
fill_mat = tf.fill((4,4),10)

In [20]:
myzeors = tf.zeros((4,4))

In [24]:
myones = tf.ones((4,4))

In [22]:
myrandn = tf.random_normal((4,4),mean=0,stddev=1)

In [23]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [25]:
my_opes = [const,fill_mat,myzeors,myones,myrandn,myrandu]

In [26]:
sess = tf.InteractiveSession()

In [30]:
for op in my_opes:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[-1.37524736 -0.13911693 -1.89365387  0.35173565]
 [-0.05224619  1.36581719 -1.14671636  0.64578068]
 [ 1.29887652 -0.3769224   0.97066748 -0.49614346]
 [-0.82045388  0.49242139 -0.85548812  0.45008925]]


[[ 0.67190349  0.67314422  0.9984771   0.90473008]
 [ 0.13903081  0.38870144  0.4378196   0.84011972]
 [ 0.99620008  0.93200898  0.36659586  0.58754838]
 [ 0.62134695  0.04724813  0.88800144  0.673944  ]]




In [36]:
a = tf.constant([[1,2],
                [3,4]])

In [37]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [35]:
b = tf.constant([[10],[100]])

In [38]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [39]:
result  = tf.matmul(a,b)

In [40]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [41]:
result.eval()

array([[210],
       [430]], dtype=int32)